### ISSUE TITLE
This works great for me, thanks!

### ISSUE THREAD

**Issue by jsaak** [jlcrochet/vim-ruby#3]
I had problems with default ruby plugin, and your version seems to fix it all!
The reason i make this issue, is that other people may be able to find your repo with a search engine when they search for the error message.
I am guessing a lot of people are having these errors:

E363: pattern uses more memory than 'maxmempattern'

'redrawtime' exceeded, syntax highlighting disabled

These are gone now!
Thanks!

**Comment by jlcrochet** [comment]
Great, glad it works for you. Performance was the main thing that prompted me to make this plugin.
