### ISSUE TITLE
This plugin breaks vim-haml

### ISSUE THREAD

**Issue by pilaf** [jlcrochet/vim-ruby#4]
First of all, thank you for vim-ruby!

It seems that this plugins breaks Haml highlighting through [vim-haml](https://github.com/tpope/vim-haml) (distributed with Vim itself) under some circumstances.

I originally thought this was a bug in vim-haml and [opened a PR for it](https://github.com/tpope/vim-haml/pull/98), but in the end that turned out not to be the case, and instead disabling your plugin fixed the issue for me.

The issue itself has to do with curly brace (`{}`) attributes in Haml, which contain Ruby. When using that syntax along with a nested hash, the result is that vim-ruby continues to syntax-highlight the rest of the file, never returning back to Haml.

Here's an example Haml snippet that breaks highlighting:

```haml
.example{ data: { foo: 'bar' } }
  %p
    The lines after the first should be highlighted as Haml, but instead
    they get highlighted as Ruby when using vim-ruby.
    This only happens when there's a nested hash in attributes as above

  class ThisShould_NOT_BeHighlightedAsRuby
  end
```

I'd still like to use your plugin, but since I work with a lot of Haml files I'm unable to. I understand this may not be a bug that affects you though, so if you decide not to look into it that's perfectly OK, but I thought I'd bring it to your attention at least.

**Comment by jlcrochet** [comment]
Hi, thanks for bringing this to my attention.

After taking a look at vim-haml, it appears there's no easy fix that will make my files compatible with theirs. The best I can do is make a fork of vim-haml that will be compatible with my files instead. I'll try to get around to that later this week.

**Comment by pilaf** [comment]
That's awesome, thank you.

**Comment by jlcrochet** [comment]
Since this issue will inevitably affect anyone who uses this plugin and wants to write HAML, I decided to incorporate HAML support directly into this plugin instead of making a fork of vim-haml. It should work out of the box with no additional configuration required.

I tested it as thoroughly as I could, but since I don't use HAML on a regular basis, there may be some things that I missed. I would appreciate any feedback you can give once you have a chance to try it.

**Comment by pilaf** [comment]
I'm now using your new version with Haml support. I don't have much feedback yet, other than it seems to work well so far 👍 . I will take notes in the following days if I notice anything worth commenting on.

Thanks again for the great plugin!
