### ISSUE TITLE
Haml highlighter doesn't highlight Ruby for interpolated strings at beginning of line

### ISSUE THREAD

**Issue by pilaf** [jlcrochet/vim-ruby#5]
Hey again 👋 ,

I found a small bug in the new Haml highlighter.

In Haml you can use `#{}` for interpolating Ruby into a line of text, e.g.:

```haml
%p Hey there, my name is #{@name}
```

The new Haml syntax highlighter knows about this, but fails to detect it when the interpolation is at the beginning of its own line, e.g.:

```haml
%p
  Hey there, my name is
  #{@name}.
```

Screenshot:

<img width="248" alt="Screenshot 2023-06-23 at 4 13 28 PM" src="https://github.com/jlcrochet/vim-ruby/assets/38060/fea78490-61e7-4b34-ba9e-b6f681c760a8">

**Comment by jlcrochet** [comment]
Okay, I think this issue should be fixed now.

**Comment by pilaf** [comment]
It does appear to be fixed, but I think maybe a new bug was introduced. I'm not entirely sure if the two are related as I don't know how to go back to the previous version to compare, but I'm reporting it here as if they were for now:

The following is now causing Vim to freeze:

Create a Haml file with the following:

```haml
%div{ foo: {
} }
```

Position the cursor on line 2 and press `o` to enter a new line. At this point Vim freezes for me and I can't neither type nor go back to normal mode.

**Comment by jlcrochet** [comment]
That's weird, it doesn't do that for me. Once Vim freezes, try hitting Ctrl+C and see if that breaks out of the loop, then check `:mes` to see if there is any indication as to which file might be causing the problem. Otherwise, you can try sending me your .vimrc and I can try running it myself.
